name: Update Blocklist

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly at midnight on Sunday
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch blocklist from sources
        run: pnpm exec node scripts/update-blocklist.js

      - name: Commit changes if blocklist was updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet data/moderation/blocked-domains.json; then
            echo "No changes to blocklist"
          else
            git add data/moderation/blocked-domains.json
            git commit -m "Update blocked domains list"
            git push
          fi
