name: Update Blocklist

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly at midnight on Sunday
  workflow_dispatch: # Allow manual trigger

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify the pnpm version you want to use

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch blocklist from sources
        run: node scripts/update-blocklist.js

      - name: Commit changes if blocklist was updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet data/moderation/blocked-domains.json; then
            echo "No changes to blocklist"
          else
            git add data/moderation/blocked-domains.json
            git commit -m "Update blocked domains list"
            git push
          fi
