name: Update Blocklist

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly at midnight on Sunday
  workflow_dispatch: # Allow manual trigger

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch blocklist from sources
        run: node scripts/update-blocklist.js

      - name: Commit and create pull request if blocklist was updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet data/moderation/blocked-domains.json; then
            echo "No changes to blocklist"
          else
            git checkout -b update-blocklist-$(date +%Y%m%d%H%M%S)
            git add data/moderation/blocked-domains.json
            git commit -m "Update blocked domains list"
            git push origin HEAD
            gh pr create --title "Update blocked domains list" --body "Automated PR to update the blocked domains list." --base main
          fi
